In [5]:
import pandas

In [6]:
serie=pandas.Series([11,15,12,13,14,12,11,11,10,14,16,16,14])
print(serie)

0     11
1     15
2     12
3     13
4     14
5     12
6     11
7     11
8     10
9     14
10    16
11    16
12    14
dtype: int64

In [7]:
serie=pandas.Series([11,15,12,13,14,12,11,11,10,14,16,16,14], index=["Fred", "Jeanne", "Julie","Julien", "chloé","Alex",
"Nicolas", "Alice", "Mathéo", "Zoé", "Mael", "Cathérine", "Ines" ])
print(serie)

Fred         11
Jeanne       15
Julie        12
Julien       13
chloé        14
Alex         12
Nicolas      11
Alice        11
Mathéo       10
Zoé          14
Mael         16
Cathérine    16
Ines         14
dtype: int64

In [8]:
#Cette fonction permet de donner une distribution dans une série pandas#
serie.describe()

count    13.0
mean     13.0
std       2.0
min      10.0
25%      11.0
50%      13.0
75%      14.0
max      16.0
dtype: float64

In [11]:
serie[["Julien", "Julie", "Mathéo"]]

Julien    13
Julie     12
Mathéo    10
dtype: int64

In [12]:
serie.mean()

np.float64(13.0)

In [13]:
serie.max()

np.int64(16)

In [14]:
serie[serie>12]

Jeanne       15
Julien       13
chloé        14
Zoé          14
Mael         16
Cathérine    16
Ines         14
dtype: int64

In [16]:
#Dataframe:c'est une structure de données ayant en ligne des observations(individus et en ligne les attributs décrivants ses individus#
import numpy as np

In [28]:
houses =houses=np.genfromtxt("Houses.csv" , delimiter=",", dtype=int )

print(houses)

[[212000   4148  25264]
 [230000   2501  11891]
 [339000   4374  25351]
 [289000   2398  22215]
 [160000   2536   9234]
 [ 85000   2368  13329]
 [ 85000   1264   8407]
 [145000   1572  12588]
 [164000   2375  16204]
 [123500   1161   9626]
 [180000   1542   8755]
 [159500   1464  14636]
 [156000   2240  21780]
 [146500   1269  11250]
 [101500    924   7361]
 [109800    768  10497]
 [182000   1320  15768]
 [110000   1845  12153]
 [125000   1274  13634]
 [ 80000   1905  10890]]

In [ ]:
dataframe= pandas.DataFrame(houses, columns=["prix", "Taille de la maison", "Surface de la maison"])
(dataframe)

      prix  Taille de la maison  Surface de la maison
0   212000                 4148                 25264
1   230000                 2501                 11891
2   339000                 4374                 25351
3   289000                 2398                 22215
4   160000                 2536                  9234
5    85000                 2368                 13329
6    85000                 1264                  8407
7   145000                 1572                 12588
8   164000                 2375                 16204
9   123500                 1161                  9626
10  180000                 1542                  8755
11  159500                 1464                 14636
12  156000                 2240                 21780
13  146500                 1269                 11250
14  101500                  924                  7361
15  109800                  768                 10497
16  182000                 1320                 15768
17  110000                 1845                 12153
18  125000                 1274                 13634
19   80000                 1905                 10890

In [29]:
groupe1=pandas.Series([11,15,12,13,14,12,11,11,10,14,16,16,14], index=["Fred", "Jeanne", "Julie","Julien", "chloé","Alex",
"Nicolas", "Alice", "Mathéo", "Zoé", "Mael", "Cathérine", "Ines" ])
print(groupe1)

Fred         11
Jeanne       15
Julie        12
Julien       13
chloé        14
Alex         12
Nicolas      11
Alice        11
Mathéo       10
Zoé          14
Mael         16
Cathérine    16
Ines         14
dtype: int64

In [31]:
groupe2=pandas.Series([11,15,15,11,14,12,11,13,10,14,16,16,9], index=["Fred", "Jeanne", "Damien", "Grace", "Chloé", "Alex", "Nicolas",
"Julien", "Mathéo", "Zoé", "Mael", "Cathérine", "Samuel"])

In [32]:
#pour créer un dataframe avec les listes on utilise les dictionnaires#
dataframe=pandas.DataFrame({"Groupe1" : groupe1, "Groupe2" :groupe2})

In [33]:
dataframe

           Groupe1  Groupe2
Alex          12.0     12.0
Alice         11.0      NaN
Cathérine     16.0     16.0
Chloé          NaN     14.0
Damien         NaN     15.0
Fred          11.0     11.0
Grace          NaN     11.0
Ines          14.0      NaN
Jeanne        15.0     15.0
Julie         12.0      NaN
Julien        13.0     13.0
Mael          16.0     16.0
Mathéo        10.0     10.0
Nicolas       11.0     11.0
Samuel         NaN      9.0
Zoé           14.0     14.0
chloé         14.0      NaN